export { default as CLEAN_HANDS } from './clean-hands.svg'
export { default as DOCTOR } from './doctor.svg'
export { default as FLU_MASK } from './flu-mask.svg'
export { default as HEALTHCARE } from './healthcare.svg'
export { default as NEWS } from './news.svg'
export { default as SOCIAL_DISTANCING } from './social-distancing.svg'
export { default as FLAG_PH } from './flag-ph.svg'
export { default as TIME } from './time.svg'
